# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d1759f33f33c923c1d36231a4fc44f001bb5c75dbd302f6f01e9d7e7c4a70046295b3a9646403ab6607bda30289907c11161898cf7066cd7b08179187b02978

test:
  secret_key_base: 46e23aedfc7ce719a47fa008176640bd9b701c4e6d3c7cbee40c89d735a0d51c1ea1557099ae39c2e298797b40761283a2177ac9282ef73f5bca61353425a52d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
